<nav class="navbar">
    <ul class="navbar-itens">
        <li><a href="/">OKR</a></li>
        <li><a href="/objective"><i class="fa-solid fa-plus"></i> Objetivo</a></li>
        <li><a href="/key-result"><i class="fa-solid fa-plus"></i> Resultado Chave</a></li>
        <li><a href="/objective/list"><i class="fa-solid fa-list"></i> Minhas OKRs</a></li>
        <li><a href="/user/logout"><i class="fa-solid fa-door-open"></i> Sair</a></li>
    </ul>
</nav>