<?php
    /** @var $args array */
    /** @var $viewName */
    /** @var $viewNavbar */

    $flash = $_SESSION['flash'] ?? false;
    unset($_SESSION['flash']);
?>

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../../assets/css/base.css?v=<?= time() ?>">
    <link rel="stylesheet" href="../../../assets/css/style.css?v=<?= time() ?>">
    <title><?= $args['title'] ?></title>
    <script src="../../../assets/jQuery/jquery-3.7.0.min.js?v=<?= time() ?>" type="text/javascript"></script>
    <script src="https://kit.fontawesome.com/9328e4f09b.js" crossorigin="anonymous"></script>
</head>
<body>
<?php
    if (!in_array($viewName, ['login', 'register'])) {
        include_once $viewNavbar;
    }
 ?>
<main class="container">
    <?php if($flash): ?>
        <div class="flash ">
            <button class="close-flash btn btn-outline">&times;</button>
            <span><?= $flash ?></span>
        </div>
    <?php endif;?>
