<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../../assets/css/style.css?v=<?= time() ?>">
    <title><?= $_GET['title'] ?></title>
    <script src="../../../assets/jQuery/jquery-3.7.0.min.js?v=<?= time() ?>" type="text/javascript"></script>
    <script src="https://kit.fontawesome.com/9328e4f09b.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar">
        <ul class="navbar-itens">
            <li><a href="/">OKR</a></li>
            <li><a href="/objective"><i class="fa-solid fa-plus"></i> Objetivo</a></li>
            <li><a href="/key-result"><i class="fa-solid fa-plus"></i> Resultado Chave</a></li>
            <li><a href="/objective/list"><i class="fa-solid fa-list"></i> Minhas OKRs</a></li>
            <li><a href="/user/logout"><i class="fa-solid fa-door-open"></i> Sair</a></li>
        </ul>
    </nav>