<?php
/**
 * @var $args array
 */
?>

<main class="container">
    <section>
        <form method="POST" id="objective-form" class="form">
            <h2>Adicionar Objetivo</h2>
            <div class="form-group ">
                <label for="title"><span>Título</span></label>
                <input type="text" name="title" id="title" class="input-form" placeholder="Informe o título" value="<?= $args['oldData']['title'] ?? '' ?>" required>
            </div>
            <div class="form-group">
                <label for="description"><span>Descrição</span></label>
                <input type="text" id="description" class="input-form" placeholder="Informe a descrição" name="description" value="<?= $args['oldData']['description'] ?? '' ?>" required>
            </div>
            <div class="form-group">
                <input type="text" class="input-form hide" name="id" value="<?= $args['oldData']['id'] ?? '' ?>">
            </div>
            <button class="btn" type="submit"><i class="fa-solid fa-plus"></i> Adicionar</button>
            <a class="btn" href="<?= $_SERVER['HTTP_REFERER']; ?>"><i class="fa-solid fa-arrow-left"></i> Voltar</a>
        </form>
    </section>
</main>

<script src="../../assets/js/objective.js?v=<?= time() ?>" type="text/javascript"></script>