<?php
/**
 * @var $args array
 */
?>

<main class="container">
    <h2 class="text-center">Minhas OKRs</h2>
    <div class="cards">
        <?php foreach ($args['objectives'] as $objective): ?>
                <?php if(!$objective['deleted_at']): ?>
                    <div class="card-body">
                        <?php $keyResults = $args['keyResultsModel']->list($objective['id']); ?>

                        <div class="objective-group">
                            <h3>Objetivo: <?php echo $objective['title']; ?></h3>
                            <h4>Descrição: <?php echo $objective['description']; ?></h4>

                            <div class="action">
                                <button class="btn btn-warning" id="objective_edit_button" value="<?= $objective['id'];?>"><i class="fa-solid fa-pen"></i></button>
                                <button class="btn btn-danger" id="objective_remove_button" value="<?= $objective['id'];?>"><i class="fa-solid fa-trash"></i></button>
                            </div>
                        </div>

                        <?php if ($keyResults): ?>
                            <div class="key-result-group">
                                <hr class="separator">
                                <h3>Resultados Chave</h3>
                                <?php foreach ($keyResults as $key => $keyResult): ?>
                                    <?php if(!$keyResult['deleted_at']): ?>
                                        <h3><?php echo $keyResult['title']; ?></h3>

                                            <h4><strong>Descrição</strong>: <?=$keyResult['description']?></h4>
                                            <h5><strong>Tipo</strong>: <?= $keyResult['type'] == 1 ? 'Milestone' : 'Porcentagem'   ?></h5>

                                        <div class="action">
                                            <button class="btn btn-danger" id="key_result_edit_button" value="<?= $keyResult['id'];?>"><i class="fa-solid fa-pen"></i></button>
                                            <button class="btn btn-warning" id="key_result_remove_button" value="<?= $keyResult['id'];?>"><i class="fa-solid fa-trash"></i></button>
                                        </div>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
        <?php endforeach; ?>
        </div>
        <div class="control">
            <a class="btn btn-primary" href="/"><i class="fa-solid fa-house"></i></a>
        </div>
    </section>
</main>

<script src="../../assets/js/key-results.js?v=<?= time() ?>" type="text/javascript"></script>
<script src="../../assets/js/objective.js?v=<?= time() ?>" type="text/javascript"></script>