<main class="container">
    <section class="form text-center">
        <h2>Login</h2>

        <form method="POST" id="login-form" >
            <div class="form-group">
                <label for="email">
                    <span>Email: </span>
                    <input type="email" placeholder="Digite aqui o e-mail" id="email" name="email" required>
                </label>
            </div>
            <div class="form-group">
                <label for="password">
                    <span>Senha: </span>
                    <input type="password" placeholder="Digite aqui a senha" id="password" name="password" required>
                </label>
            </div>
            <button class="btn" type="submit">Entrar</button>
        </form>
        <a href="/user/register" class="btn">Cadastrar</a>
    </section>
</main>

<script src="../../assets/js/login.js" type="text/javascript"></script>
