<main class="container">
    <section class="form text-center">
        <h2>Login</h2>
        <form method="POST" id="login-form" >
            <div class="">
                <label for="email">
                    <span>Email: </span>
                    <input type="email" placeholder="Digite aqui o e-mail" id="email" name="email" value="a@a.com"  autofocus>
                </label>
            </div>
            <div>
                <label for="password">
                    <span>Senha: </span>
                    <input type="password" placeholder="Digite aqui a senha" id="password" name="password" value="12345678" >
                </label>
            </div>
            <div>
                <button class="btn" type="submit">
                    Logar
                </button>
            </div>
        </form>
        <a href="cadastro.php" class="btn">Cadastrar</a>
    </section>
</main>

<script src="../../assets/js/user.js" type="text/javascript"></script>
<script src="../../assets/js/objective.js" type="text/javascript"></script>
<script src="../../assets/js/login.js" type="text/javascript"></script>
