<main class="container">
    <section class="form login">
        <div class="field">

            <form method="POST" id="login-form" >
                <h2>Login</h2>
                <div class="form-group">
                    <label for="email"><span>Email</span></label>
                    <input type="email" placeholder="Informe o e-mail" id="email" class="input-form" name="email" required>
                </div>
                <div class="form-group">
                    <label for="password"><span>Senha</span></label>
                    <input type="password" placeholder="Informe a senha" id="password" class="input-form" name="password" required>
                </div>
                <button class="btn" type="submit">Entrar</button>
                <a href="/user/register" class="btn">Cadastrar</a>
            </form>
        </div>
    </section>
</main>

<script src="../../assets/js/login.js" type="text/javascript"></script>
