<main class="container">
    <section class="text-center">
        <h2>Cadastro</h2>

        <form method="POST" id="user-form">
            <div class="form-group">
                <label for="nome">
                    <span>Nome: </span>
                    <input type="text" name="name" id="name" required>
                </label>
            </div>
            <div class="form-group">
                <label for="email">
                    <span>Email: </span>
                    <input type="email" id="email" name="email" required>
                </label>
            </div>
            <div class="form-group">
                <label for="password">
                    <span>Senha: </span>
                    <input type="password" id="password" name="password" required>
                </label>
            </div>

            <div class="form-group">
                <label for="password-check">
                    <span>Confirmação da Senha: </span>
                    <input type="password" id="password-check" name="password-check" required>
                </label>
            </div>

            <div>
            <button type="submit" class="btn">Enviar</button>
            </div>
        </form>
    </section>
</main>

<script src="../../assets/js/user.js" type="text/javascript"></script>