<main class="container">
    <section class="text-center">
        <h2>Criar usuário</h2>
        <form method="POST" id="user-form">
            <div class="">
                <label for="nome">
                    <span>Nome: </span>
                    <input type="text" name="name" id="name" value="">
                </label>
            </div>
            <div class="">
                <label for="email">
                    <span>Email: </span>
                    <input type="email" id="email" name="email" value="email@email.com">
                </label>
            </div>
            <div>
                <label for="password">
                    <span>Senha: </span>
                    <input type="password" id="password" name="password" value="123456789">
                </label>
            </div>

            <div>
                <button type="submit" class="btn">
                    ENVIAR
                </button>
            </div>
        </form>
    </section>
</main>
<footer></footer>
<script src="../../assets/js/user.js" type="text/javascript"></script>