<section class="cards center-card">
    <div class="card-body">
        <form method="POST" id="user-form">
            <h2>Cadastro</h2>
            <div class="form-group">
                <label for="nome"><span>Nome</span></label>
                <input type="text" placeholder="Informe o Nome" name="name" class="input-form" id="name" required>
            </div>
            <div class="form-group">
                <label for="email"><span>E-mail</span></label>
                <input type="email" placeholder="Informe o e-mail" id="email" class="input-form" name="email" required>
            </div>
            <div class="form-group">
                <label for="password"><span>Senha</span></label>
                <input type="password" placeholder="Informe a Senha" id="password" class="input-form" name="password" required>
            </div>

            <div class="form-group">
                <label for="password-check"><span>Confirmação da Senha</span></label>
                <input type="password" placeholder="Informe a senha novamente" id="password-check" class="input-form" name="password-check" required>
            </div>
            <div class="action">
                <button type="submit" class="btn btn-custom"><i class="fa-regular fa-user"></i> Cadastrar</button>
            </div>
            <div class="text-center">
                <a href="/">Já é cadastrado?</a>
            </div>
        </form>
    </div>
</section>

<script src="../../assets/js/auth/user.js?v=<?= time() ?>" type="text/javascript"></script>