<main class="container">
    <section class="home">
        <div class="text-center jumbotron">
            <h2>OKR: OBJECTIVE KEY RESULTS</h2>
            <p>É uma metodologia de definição de metas a partir de objetivos chaves</p>
        </div>

        <h3>Objetivo</h3>
        <p>Os objetivos são definidos a nível <strong>estratégico</strong> ou <strong>operacionais</strong>.</p>

        <h3>Resultados chave</h3>
        <p>São medidos por <strong>milestones</strong> ou <strong>valores</strong>.</p>
    </section>
</main>
