<nav>

</nav>

<main>
    <section class="jumbotron text-center">
        <h2>OKR: OBJECTIVE KEY RESULTS</h2>
        <p>É uma metodologia de definição de metas a partir de objetivos chaves</p>
        <h4>Objetivo</h4>
        <p>Os objetivos são definidos a nível <strong> estratégico </strong> ou operacionais. </p>
        <h4>Resultados chave</h4>
        <p>São medidos por milestones ou valores</p>
        <p></p>
    </section>

    <section class="text-center">
        <h2>Adicionar Objetivo usuário</h2>
        <form method="POST" id="objective-form" class="form">
            <div class="">
                <label for="title">
                    <span>Título: </span>
                    <input type="text" name="title" id="title" value="">
                </label>
            </div>

            <div class="">
                <label for="description">
                    <span>Descrição: </span>
                    <input type="text" id="description" name="description" value="">
                </label>
            </div>

            <div>
                <button class="btn" type="submit">
                    ENVIAR
                </button>
            </div>
        </form>
    </section>

    <section>
        <h2>Links úteis</h2>

        <a class="btn" href="/key-result">Adicionar key result</a>
        <a class="btn" href="/objective/list">Listar meus objetivos</a>
        <a class="btn" href="/user/logout">Sair</a>
    </section>
</main>

<script src="../../assets/js/user.js?v=<?= time() ?>" type="text/javascript"></script>
<script src="../../assets/js/objective.js?v=<?= time() ?>" type="text/javascript"></script>
<script src="../../assets/js/login.js?v=<?= time() ?>" type="text/javascript"></script>

